name: ffmpeg
on:
  push:
    paths:
      - ffmpeg/**
      - .github/workflows/ffmpeg.yml
  pull_request:
    paths:
      - ffmpeg/**
      - .github/workflows/ffmpeg.yml
  workflow_dispatch:
env:
  CI_DEPLOY_NEED_GCC: 1
  CI_DEPLOY_MODULE: ${{ github.workflow }}
  CI_DEPLOY_PLATFORM: ${{ github.job }}
  CI_DEPLOY_SETTINGS: ${{ secrets.CI_DEPLOY_SETTINGS }}
  CI_DEPLOY_USERNAME: ${{ secrets.CI_DEPLOY_USERNAME }}
  CI_DEPLOY_PASSWORD: ${{ secrets.CI_DEPLOY_PASSWORD }}
  STAGING_REPOSITORY: ${{ secrets.STAGING_REPOSITORY }}
jobs:
#  android-arm:
#    runs-on: ubuntu-20.04
#    container: centos:7
#    strategy:
#      matrix:
#        ext: ["", -gpl]
#    steps:
#      - uses: actions/checkout@v3
#      - uses: ./.github/actions/deploy-centos
#  android-arm64:
#    runs-on: ubuntu-20.04
#    container: centos:7
#    strategy:
#      matrix:
#        ext: ["", -gpl]
#    steps:
#      - uses: actions/checkout@v3
#      - uses: ./.github/actions/deploy-centos
#  android-x86:
#    runs-on: ubuntu-20.04
#    container: centos:7
#    strategy:
#      matrix:
#        ext: ["", -gpl]
#    steps:
#      - uses: actions/checkout@v3
#      - uses: ./.github/actions/deploy-centos
#  android-x86_64:
#    runs-on: ubuntu-20.04
#    container: centos:7
#    strategy:
#      matrix:
#        ext: ["", -gpl]
#    steps:
#      - uses: actions/checkout@v3
#      - uses: ./.github/actions/deploy-centos
#  linux-armhf:
#    runs-on: ubuntu-20.04
#    container: ubuntu:bionic
#    strategy:
#      matrix:
#        ext: ["", -gpl]
#    steps:
#      - uses: actions/checkout@v3
#      - uses: ./.github/actions/deploy-ubuntu
#  linux-arm64:
#    runs-on: ubuntu-20.04
#    container: ubuntu:bionic
#    strategy:
#      matrix:
#        ext: ["", -gpl]
#    steps:
#      - uses: actions/checkout@v3
#      - uses: ./.github/actions/deploy-ubuntu
#  linux-ppc64le:
#    runs-on: ubuntu-20.04
#    container: ubuntu:bionic
#    strategy:
#      matrix:
#        ext: ["", -gpl]
#    steps:
#      - uses: actions/checkout@v3
#      - uses: ./.github/actions/deploy-ubuntu
#  linux-x86:
#    runs-on: ubuntu-20.04
#    container: centos:7
#    strategy:
#      matrix:
#        ext: ["", -gpl]
#    steps:
#      - uses: actions/checkout@v3
#      - uses: ./.github/actions/deploy-centos
  linux-x86_64:
    runs-on: ubuntu-20.04
    container: quay.io/fedora/fedora:37
    strategy:
      matrix:
        ext: [""]
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/deploy-fedora
#  macosx-arm64:
#    runs-on: macos-11
#    strategy:
#      matrix:
#        ext: ["", -gpl]
#    steps:
#      - uses: actions/checkout@v3
#      - uses: ./.github/actions/deploy-macosx
#  macosx-x86_64:
#    runs-on: macos-11
#    strategy:
#      matrix:
#        ext: ["", -gpl]
#    steps:
#      - uses: actions/checkout@v3
#      - uses: ./.github/actions/deploy-macosx
#  windows-x86:
#    runs-on: windows-2019
#    strategy:
#      matrix:
#        ext: ["", -gpl]
#    steps:
#      - uses: actions/checkout@v3
#      - uses: ./.github/actions/deploy-windows
#  windows-x86_64:
#    runs-on: windows-2019
#    strategy:
#      matrix:
#        ext: ["", -gpl]
#    steps:
#      - uses: actions/checkout@v3
#      - uses: ./.github/actions/deploy-windows
  redeploy:
    needs: [linux-x86_64]
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/redeploy
